from . import table_settings
from . import localitation
from . import hr_leave
from . import hr_contract
from . import hr_employee
from . import hr_payslip
from . import hr_payslip_run
from . import hr_provisions
from . import hr_payroll_period
from . import hr_inputs
from . import import_inputs
from . import res_config_settings
from . import hr_salary_rule
from . import hr_isn
from . import hr_payroll_account
from . import annual_isr_adjustment
from . import hr_ptu
