# -*- coding: utf-8 -*-
{
    "name": "Customization of the human resources process for Mexico.",
    'author': 'Soluciones Softhard, C.A.',
    'website': 'http://www.solucionesofthard.com',
    "category": "Human Resources",
    "description": "Module that adapts Mexico's own characteristics of the human resources process.",
    'summary': "Module that adapts Mexico's own characteristics of the human resources process.",
    "depends": ['base', 'hr_payroll', 'hr_work_entry_contract', 'import_employees', 'hr', 'hr_employe_mexico', 'hr_holidays_edi_mx', 'base_mexico','hr_payroll_account'],
    "data": [
        'security/ir.model.access.csv',
        'security/payroll_mexico_security.xml',

        'data/ir_sequence_data.xml',
        'data/data_work_entry_type.xml',
        'data/ir_cron_methods.xml',

        'views/assets.xml',
        'views/table_settings_views.xml',
        'views/localitation_views.xml',
        'views/hr_leave.xml',
        'wizard/hr_payroll_payslips_by_employees_views.xml',
        'wizard/reverse_calculation_salary_views.xml',
        'wizard/vacation_premium_allowance_view.xml',
        'wizard/annual_isr_adjustment_employee_views.xml',
        'views/hr_contract.xml',
        'views/hr_payslip.xml',
        'views/hr_provisions_views.xml',
        'views/hr_payslip_run_views.xml',
        'views/hr_payroll_period_views.xml',
        'views/hr_inputs_views.xml',
        'wizard/hr_payroll_period_generate_view.xml',
        'views/res_config_settings_views.xml',
        'views/hr_salary_rule.xml',
        'views/import_inputs.xml',
        'views/hr_payroll_account_view.xml',
        'views/annual_isr_adjustment_views.xml',
        'data/data_table_settings.xml',
        'data/data_isn.xml',
        'data/hr_payroll_data.xml',
        'report/report_templates.xml',
        'report/report_payslip_templates.xml',
        'report/report_settlement.xml',
        'views/annual_isr_adjustment_views.xml',
        'wizard/hr_ptu_employees_views.xml',
        'views/hr_ptu_views.xml',
    ],
    "active": True,
    "installable": True,
}

