from . import employee_change
from . import massive_employee_modification
from . import contract_change
from . import hr_employee_document_import
from . import wizard_generate_reports
from . import change_salary_tab
from . import tab_change
from . import wizard_low_position
from . import import_signatures_users
from . import import_images_employees
